status: fix QString handling on null chunk list received
Because `hash(QString('foo'))` is different from `hash('foo')`,
`wfile in self.partials` is always false if wfile is a QString.

With this change, partial selection is cleared once fileview leaves DiffMode.
Thus, the following exception no longer happen:

    Traceback (most recent call last):
      File "tortoisehg\hgqt\status.pyo", line 469, in checkToggled
      File "tortoisehg\hgqt\fileview.pyo", line 289, in updateChunk
    AttributeError: 'NoneType' object has no attribute 'excludecount'

when:

 1. uncheck one chunk
 2. change view to FileMode
 3. uncheck file