settings: remove redundant activatePage() which may raise exception
pageList.setCurrentRow() should call activatePage().

Also it raises the following exception if the specified page name is valid
but not included in the list:

    Traceback (most recent call last):
      File "thg/tortoisehg/hgqt/settings.py", line 1399, in <lambda>
        self.activatePage(i))
      File "thg/tortoisehg/hgqt/settings.py", line 1297, in activatePage
        if item.text() == data[0]['label']:
    AttributeError: 'NoneType' object has no attribute 'text'

Because pageList does not always contain all of INFO items, focusPage() and
activepagename may still be wrong. But at least, it won't raise exception.