overlay: reorder imports, catch certain ImportErrors
It seems the overlay server can be started during an upgrade, which causes
some real havoc.  Try to catch these errors and safely exit.

Traceback (most recent call last):
  File "TortoiseHgOverlayServer.py", line 19, in <module>
  File "win32event.pyo", line 12, in <module>
  File "win32event.pyo", line 10, in __load
ImportError: DLL load failed: The process cannot access the file because it is being used by another process.