filedata: return early from ctx.sub() failure to avoid further exception
If ctx.sub() raises Abort, it continues with srepo=None and causes the
following error:

    matchfn = scmutil.match(repo[None], pats, opts)
    TypeError: 'NoneType' object is unsubscriptable

It happens if you have svn subrepo but svn executable doesn't exist.